@startuml
left to right direction

actor Usuario as U
rectangle ImageDoc {
  usecase "Realizar Upload de Arquivo" as Upload
  usecase "Criar Coleção" as CriarColecao
  usecase "Visualizar Documento" as Visualizar
  usecase "Editar Documento" as Editar
  usecase "Definir Acesso" as DefinirAcesso
  usecase "Revogar Acesso" as RevogarAcesso
  usecase "Selecionar Texto" as SelecionarTexto
  usecase "Realizar Tradução" as RealizarTraducao

}

U --> Upload
U --> CriarColecao
U --> Visualizar
U --> Editar
U --> DefinirAcesso
U --> RevogarAcesso
U --> SelecionarTexto
U --> RealizarTraducao
@enduml


___

@startuml
|Início|
start
:Usuário acessa página de upload;
:Exibir interface de upload;
:Usuário seleciona arquivo;
|Fork|
fork
  :Validar arquivo;
fork again
  :Enviar arquivo para armazenamento;
  :Armazenar arquivo;
  :Registrar metadados do arquivo;
end fork
|Upload Concluído|
end
@enduml
